Repository freifunkMUC/site-ffm, pull requests merged in 2023-12, with the labels that each got.

#309 domains: make ffdon/donau-ries public
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
Labels: stable, backport next

#313 domains: disable eol-ssid for ffdon
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
Labels: legacy

#312 [Backport legacy] domains: make ffdon/donau-ries public
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
Labels: legacy

#311 modules: harden packages incl. mesh-vpn-wireguard
  modules
Labels: stable, backport next

#316 modules: add ffdon-domain-merge
  modules
  site.mk
Labels: legacy

#317 domains: remove legacy ffdon domains
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
Labels: stable, backport legacy, backport next

#318 make ffwert_city public
  domains/ffwert_city.conf
Labels: stable, backport next

#322 domains: switch ffdon to channel 1 for 2.4 GHz
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
Labels: stable, backport legacy, backport next

#328 dockerfile: do not keep build-time artefacts
  Dockerfile_build
Labels: stable, backport legacy, backport next

#334 modules: mesh-vpn print error if NTP failed
  modules
Labels: stable, backport next

#333 [Backport legacy] site: adding signing key for ff-mgk
  site.conf
Labels: legacy

#327 Bump gluon to latest master (OpenWRT 23.05)
  Makefile
  contrib/genpkglist.py
  patches/targets-drop-TP-Link-RE305.patch
  patches/targets-drop-TP-Link-RE450-and-RE355.patch
  patches/targets-raspberry-pi-4.patch
  scripts/install_build_dependencies.sh
  site.mk
  targets
Labels: next

#336 github: downgrade upload-artifact to v3
  .github/workflows/firmware.yml
Labels: bug, stable, backport legacy, backport next

#337 [Backport next] github: downgrade upload-artifact to v3
  .github/workflows/firmware.yml
Labels: next

#338 [Backport legacy] github: downgrade upload-artifact to v3
  .github/workflows/firmware.yml
Labels: legacy

#340 contrib: add qemu guest agent as an option for x86
  contrib/genpkglist.py
  site.mk
Labels: stable, backport next

#342 contrib: remove USB and add NSM to ZyXEL NWA55AXE
  contrib/genpkglist.py
  site.mk
Labels: stable, backport next

#343 contrib: add USB For TP-Link TL-WR1043N v5
  contrib/genpkglist.py
  site.mk
Labels: stable, backport next

#341 contrib: add USB and TLS to ipq40xx-mikrotik and ath79-mikrotik
  contrib/genpkglist.py
  site.mk
Labels: stable, backport next
