Repository freifunkMUC/site-ffm, pull requests merged in 2024-12, with the labels that each got.

#516 Use Github Bot for Actions
  .github/workflows/backport.yml
  .github/workflows/bump-modules.yml
  .github/workflows/firmware.yml
  .github/workflows/shellcheck.yml
  .github/workflows/update-targets.yml
Labels: stable, backport legacy, backport next

#520 [Backport next] CI: Update to use Github App (#516)
  .github/workflows/backport.yml
  .github/workflows/bump-modules.yml
  .github/workflows/firmware.yml
  .github/workflows/shellcheck.yml
  .github/workflows/update-targets.yml
Labels: next

#521 [Backport legacy] CI: Update to use Github App (#516)
  .github/workflows/backport.yml
  .github/workflows/bump-modules.yml
  .github/workflows/firmware.yml
  .github/workflows/shellcheck.yml
  .github/workflows/update-targets.yml
Labels: gluon-v2021.1.x

#527 [gluon-v2021.1.x] github: pin firmware build to ubuntu-22.04
  .github/workflows/firmware.yml
Labels: gluon-v2021.1.x

#529 [gluon-v2023.1.x] github: pin firmware build to ubuntu-22.04
  .github/workflows/firmware.yml
Labels: gluon-v2023.1.x

#528 [gluon-v2023.2.x] github: pin firmware build to ubuntu-22.04
  .github/workflows/firmware.yml
Labels: gluon-v2023.2.x

#525 [Backport gluon-v2023.2.x] build(deps): bump softprops/action-gh-release from 2.0.5 to 2.2.0
  .github/workflows/firmware.yml
Labels: gluon-v2023.2.x

#526 [Backport gluon-v2021.1.x] build(deps): bump softprops/action-gh-release from 2.0.5 to 2.2.0
  .github/workflows/firmware.yml
Labels: gluon-v2021.1.x
