Repository freifunkMUC/site-ffm, pull requests merged in 2024-07, with the labels that each got.

#447 site: fix device names to include cellular package
  image-customization.lua
Labels: next

#449 doamins/site: remove vim annotations
  domains/ffmuc_augsburg.conf
  domains/ffmuc_freising.conf
  domains/ffmuc_gauting.conf
  domains/ffmuc_muc_cty.conf
  domains/ffmuc_muc_nord.conf
  domains/ffmuc_muc_ost.conf
  domains/ffmuc_muc_sued.conf
  domains/ffmuc_muc_west.conf
  domains/ffmuc_uml_nord.conf
  domains/ffmuc_uml_ost.conf
  domains/ffmuc_uml_sued.conf
  domains/ffmuc_uml_west.conf
  domains/ffmuc_welt.conf
  site.conf
Labels: backport legacy, backport next

#452 Add workflow to automatically update targets file
  .github/workflows/update-targets.yml
  Makefile
Labels: stable, backport legacy, backport next

#461 github: use org wide funding
  .github/FUNDING.yml
Labels: stable, backport legacy, backport next

#460 github: reduce dependabot interval
  .github/dependabot.yml
Labels: stable

#448 backport Gluon modules Updater
  .github/workflows/bump-modules.yml
  contrib/actions/update-modules.sh
Labels: stable, backport legacy

#469 patch: fritzbox-7530: utilize lan1 as wan
  patches/fritzbox-7530-7520-lan1-as-wan-pr3312.patch
Labels: next
