Repository freifunkMUC/site-ffm, pull requests merged in 2024-06, with the labels that each got.

#418 modules: improve and fix ffac-ssid-changer
  modules
Labels: stable, backport next

#419 modules: ffmuc-mesh-vpn-wireguard: Cleanup Code
  modules
Labels: stable, backport legacy, backport next

#422 fix experimental and add write permissions for workflows and pin workflow Versions
  .github/workflows/backport.yml
  .github/workflows/bump-modules.yml
  .github/workflows/firmware.yml
Labels: stable

#424 [Backport legacy] fix experimental and add write permissions for workflows and pin workflow Versions
  .github/workflows/backport.yml
  .github/workflows/firmware.yml
Labels: legacy

#423 [Backport next] fix experimental and add write permissions for workflows and pin workflow Versions
  .github/workflows/backport.yml
  .github/workflows/firmware.yml
Labels: next

#426 site: add ffmuc-custom-banner
  modules
  site.conf
  site.mk
Labels: stable, backport next

#425 [Backport legacy] modules: ffmuc-mesh-vpn-wireguard: Cleanup Code
  modules
Labels: legacy

#428 [Backport next] site: add ffmuc-custom-banner
  image-customization.lua
  modules
  site.conf
Labels: next

#427 modules: fix ffac-ssid-changer control flow
  modules
Labels: stable, backport next

#431 modules: ffmuc-mesh-vpn-wireguard improve nslookup
  modules
Labels: stable, backport legacy, backport next

#434 bump Gluon to v2023.2.3
  Makefile
Labels: next

#429 modules: add shell minifier for checkuplink
  modules
Labels: stable, backport legacy, backport next

#441 contrib: rework update-modules to fix race cond.
  contrib/actions/update-modules.sh
Labels: stable

#437 github: code higlight for domains folder .gitattributes
  .gitattributes
Labels: backport legacy, backport next
