Repository freifunkMUC/site-ffm, pull requests merged in 2024-04, with the labels that each got.

#392 site: update opkg to latest 19.07.10 release
  site.conf
Labels: legacy

#395 [Backport legacy][actions] update to latest action using node20 instead of deprecated …
  .github/workflows/backport.yml
  .github/workflows/firmware.yml
  .github/workflows/shellcheck.yml
Labels: legacy

#396 [Backport legacy] domains: add Wertingen domains
  domains/ffwert_city.conf
  domains/ffwert_events.conf
Labels: legacy

#394 Bump Gluon to latest v2021.1.x
  Makefile
Labels: legacy

#397 [Backport legacy] modules: use latest packages for ffmuc-mesh-vpn-wireguard and ffmuc-ipv6-ra-filter
  domains/ffdon_mitte.conf
  domains/ffdon_nordwest.conf
  domains/ffdon_sued.conf
  domains/ffmuc_augsburg.conf
  domains/ffmuc_freising.conf
  domains/ffmuc_gauting.conf
  domains/ffmuc_muc_cty.conf
  domains/ffmuc_muc_nord.conf
  domains/ffmuc_muc_ost.conf
  domains/ffmuc_muc_sued.conf
  domains/ffmuc_muc_west.conf
  domains/ffmuc_uml_nord.conf
  domains/ffmuc_uml_ost.conf
  domains/ffmuc_uml_sued.conf
  domains/ffmuc_uml_west.conf
  domains/ffmuc_welt.conf
  domains/ffwert_city.conf
  domains/ffwert_events.conf
  modules
  patches/0001-gluon-core-add-gluon-info-binary.patch
  patches/0002-gluon-mesh-vpn-wireguard-fix-empty-string-key.patch
  patches/0003-gluon-info-Add-current-domain-to-gluon-info.patch
  patches/0004-gluon-core-move-all-info-into-module.patch
  site.mk
Labels: legacy

#393 domains: add ffulm domains
  domains/ffmuc_ulm.conf
Labels: stable, backport legacy, backport next

#398 [Backport legacy] domains: add ffulm domains
  domains/ffmuc_ulm.conf
Labels: legacy

#401 Update Freifunk Ulm to Freifunk München - Ulm
  domains/ffmuc_ulm.conf
Labels: stable, backport legacy, backport next

#370 Add migration from FFULM to FFMUC
  modules
Labels: legacy

#406 Makefile: only change autoupdater branch and let autoupdater enabled
  Makefile
Labels: stable, backport legacy, backport next

#405 [CI] add Github action to bump modules commit Version
  .github/workflows/bump-modules.yml
  .github/workflows/firmware.yml
  contrib/actions/update-modules.sh
Labels: enhancement, stable, backport legacy, backport next
