Repository freifunkMUC/site-ffm, pull requests merged in 2024-10, with the labels that each got.

#492 make: bump gluon 2024.2.4
  Makefile
Labels: next

#497 [Backport next] build(deps): bump actions/upload-artifact from 4.3.3 to 4.4.3
  .github/workflows/firmware.yml
Labels: next

#496 [Backport legacy] build(deps): bump actions/upload-artifact from 4.3.3 to 4.4.3
  .github/workflows/firmware.yml
Labels: legacy

#495 Replace grep cpuinfo with nproc
  Makefile
Labels: backport legacy, backport next

#493 make: bump gluon
  Makefile
Labels: next

#502 github: cancel obsolete in-progress workflows
  .github/workflows/firmware.yml
Labels: stable, backport legacy, backport next, backport parker

#505 site: remove *GLUON_RELEASE
  site.mk
Labels: backport next

#506 ci,make: Add Build_NUMBER, CI ID or PR ID
  .github/workflows/firmware.yml
  Makefile
Labels: stable, backport legacy, backport next
