Repository freifunkMUC/site-ffm, pull requests merged in 2025-01, with the labels that each got.

#537 [Backport gluon-v2023.2.x] readme: change Docker tags to use branch name
  README.md
Labels: gluon-v2023.2.x

#536 readme: change Docker tags to use branch name
  README.md
Labels: gluon-v2023.1.x, backport gluon-v2021.1.x, backport gluon-v2023.2.x

#535 Makefile: remove next branch from build
  Makefile
Labels: gluon-v2023.1.x

#533 github actions: use new gluon-v* naming scheme
  .github/workflows/shellcheck.yml
  .github/workflows/update-targets.yml
Labels: gluon-v2023.1.x, backport gluon-v2021.1.x, backport gluon-v2023.2.x

#545 [gluon-v2023.2.x] patches: ath79: fix reset sequence for AR9344
  patches/0001-reset-ath79-fix-reset-sequence-for-AR9344.patch
Labels: gluon-v2023.2.x

#547 [gluon-next] Update to latest gluon / OpenWRT 24.10
  Makefile
  patches/0001-gluon-web-cellular-add-auth-option-to-GUI.patch
  patches/0001-kirkwood-add-Linksys-E4200-v2-Viper-Router-3240.patch
  patches/0001-reset-ath79-fix-reset-sequence-for-AR9344.patch
  patches/0001-temporary-remove-devices-with-too-little-flash.patch
  patches/0002-kirkwood-generic-fix-device-name-of-Linksys-E4200-v2.patch
  patches/0002-targets-remove-more-devices-with-small-flash.patch
  patches/fritzbox-7530-7520-lan1-as-wan-pr3312.patch
  patches/targets-raspberry-pi-4.patch
  scripts/install_build_dependencies.sh
Labels: gluon-next

#557 build(deps): bump softprops/action-gh-release from 2.2.0 to 2.2.1
  .github/workflows/firmware.yml
Labels: dependencies, gluon-main

#556 build(deps): bump softprops/action-gh-release from 2.2.0 to 2.2.1
  .github/workflows/firmware.yml
Labels: gluon-v2023.1.x, dependencies

#555 build(deps): bump softprops/action-gh-release from 2.2.0 to 2.2.1
  .github/workflows/firmware.yml
Labels: gluon-v2021.1.x, dependencies

#558 bump Gluon to latest main
  Makefile
Labels: gluon-main

#572 [CI] allow backports of workflows
  .github/workflows/backport.yml
Labels: gluon-v2023.2.x, backport gluon-v2021.1.x, backport gluon-v2023.1.x, backport gluon-main
